# -*- coding: utf-8 -*-
"""data_preprocessing_tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kd5VTOFJRmTM-_gepjXDqMcMvm0wrW5

# Data Preprocessing Tools

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the dataset

First, you need to mount your Google Drive to access files stored there. Run the following cell to mount your Drive and follow the authentication prompts.
"""

dataset= pd.read_csv("Data.csv")

x= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

print(x)

print(y)

"""## Taking care of missing data"""

from sklearn.impute import SimpleImputer

imputer= SimpleImputer(missing_values= np.nan, strategy= "mean")
x[:, 1:3]= imputer.fit_transform(x[:, 1:3])
print(x)

"""## Encoding categorical data

### Encoding the Independent Variable
"""

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct= ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])], remainder="passthrough")
x=ct.fit_transform(x)

print(x)

"""### Encoding the Dependent Variable"""

from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y= le.fit_transform(y)

print(y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x,y, test_size= 0.2, random_state=42)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""## Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train[:, 3:]= sc.fit_transform(X_train[:, 3:])
X_test[:, 3:]= sc.transform(X_test[:, 3:])